spring.application.name=Shorten


# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password= musk2006
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Auto create / update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console (optional but useful for learning)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
